wandb:
  entity: null
  resume: 'auto'

experiment:
    project: "rl" # need to be same of this file name
    prefix_dir: ""
    function: "train"  # no need to change
    save_every: 10
    eval_every: -1
    current_epoch: 1
    deepspeed_file: "1_node_8_gpus_deepspeed_zero3"
    num_node: 1
    node_index: 0

model:
    pretrained_model: "xxx/SDAR-8B-Chat" # absolute path of your model
    optimized_name: "optimized" # the output name for your optimized model, will be saved under sft_dream/ckpt
    model_base: "sdar" # set sdar for TraDo and SDAR


dataset:
    train_dataset: "MATH_train" # "MATH_train""PrimeIntellect"
    eval_dataset: "MATH500"
    optimization_data: "rl_data" # name of the rollout data output
    data_type: "math" # "math" "code" 

# also see explanations in eval configs
rollout:
    tensor_parallel_size: 1 # set to 1 by default, if oom, try reduce max_active first, if still oom, set tensor_parallel_size to 8
    num_task_per_step: 128
    num_response_per_task: 8
    temperature: 1.0
    max_token: 8192
    block_size: 4
    denoising_steps_per_block: 4
    top_p: 1.0
    top_k: 50
    remasking_strategy: "low_confidence_dynamic"
    dynamic_threshold: 0.9 # no use for "low_confidence_static"
    start_with_think: False
    speed: False

training:
    reward_funcs: "cosine"
    gradient_checkpointing_enable: True
    gradient_accumulation_steps: 1
    batch_size_lm: 1
    inner_micro_batch_size: 4
    micro_batch_size: 4 # Split forward pass into smaller batches to save memory. Set to null to disable splitting
    mixed_precision: "bf16"
    enable_tf32: True
    seed: 10086
    num_iterations: 1
    per_device_train_batch_size: 1
    save_every_iteration: False
    num_train_epochs: 240
    max_grad_norm: 1.0
    method: "TraceRL"
    block_size: 4
    shrink: 1
    post_num: 0
    max_gen_length: 8192
    max_prompt_len: 2048
    lower_p: 0.1
    upper_p: 0.9
    eps: 0.20
    beta: 0.1
    use_kl_estimator_k3: True


optimizer:
    name: adamw
    params: # default adamw params
        learning_rate: 1e-6
        scale_lr: False # scale learning rate by total batch size
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.0
        epsilon: 1e-8


lr_scheduler:
    scheduler: "constant"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 0
        min_lr_scale: 1.0


evaluation:
    eval_dataset: "MATH500"  # "MATH500" "LiveCodeBench"
    data_type: "math" # "math" "code"
    tensor_parallel_size: 1
    num_response_per_task: 16
    temperature: 1.0
    max_token: 8192
    block_size: 4
    denoising_steps_per_block: 4
    top_p: 1.0
    top_k: 50
    remasking_strategy: low_confidence_dynamic 
    dynamic_threshold: 0.9 # no use for "low_confidence_static"
    start_with_think: False
